### ISSUE TITLE
小数位多余五位，界面卡死

### ISSUE THREAD

**Issue by EarthMass** [iceyouyou/UUAmountBoardView#1]
小数位多余五位，界面卡死

**Comment by iceyouyou** [comment]
@EarthMass  Demo也会复现么？我测试了多位小数可以正常运行，如果继续复现麻烦提供一些详细信息，谢谢。

**Comment by EarthMass** [comment]
我这边使用的问题，宽度被约束了，数量大于被约束的宽度就会卡死，作者注意一下，看下能不能处理。

**Comment by iceyouyou** [comment]
@EarthMass 这个控件会按照内容自适应宽高，无论使用frame还是AutoLayout都不用指定宽高。只要能确定起始点就好了。
